### ISSUE TITLE
User Interface - Part 1

### ISSUE THREAD

**Issue by tjlauer** [tjlauer/Hospital_Simulator#24]
When the user pushes a button, show a floating user interface that shows buttons for different scenes.

**Comment by Jflyer45** [comment]
Working on making a button. The button will have event it executes (So we can program it to do anything we need.) Planning on making it a  prefab

**Comment by Jflyer45** [comment]
Button is done, it is on the button-testing branch. In it's own scene. Havn't made it a prefab yet until I can test it with UI
