### ISSUE TITLE
[BUG] Only allow controller to grab one object at a time

### ISSUE THREAD

**Issue by Jflyer45** [tjlauer/Hospital_Simulator#37]
Currently you can grab two items at once accidently. The hand sanitizer and the cart for example. When two grabbable objects are near each other this seems to happen sometimes. However adding bodies to the objects will probably fix this because they are clipping into each other.

***Edit 
Hmm. It might be a bug with my code. After going back to the Experimental branch it seems to be fine. I will try to reproduce it on video. **Don't worry about this till I have proof lol.**

**Comment by tjlauer** [comment]
Steps to reproduce? Can you get a screen recording of it?

**Comment by tjlauer** [comment]
@Jflyer45 don't edit your posts. Instead, add a comment to the issue thread.
