### ISSUE TITLE
Fix package version changes in "Packages/packages-lock.json"

### ISSUE THREAD

**Issue by tjlauer** [tjlauer/Hospital_Simulator#57]
## The Problem
Depending on who commits a change to a branch, for the ```"com.unity.xr.interactionsubsystems"``` dependency, the minimum version requirement for secondary  dependency `"com.unity.subsystemregistration"` flips between `"1.0.5"` and `"1.0.6"`.

i.e. the file changes between
```JSON
"com.unity.xr.interactionsubsystems": {
    "version": "1.0.1",
    "depth": 1,
    "source": "registry",
    "dependencies": {
        "com.unity.subsystemregistration": "1.0.5"
    },
    "url": "https://packages.unity.com"
}
```
and
```JSON
"com.unity.xr.interactionsubsystems": {
    "version": "1.0.1",
    "depth": 1,
    "source": "registry",
    "dependencies": {
        "com.unity.subsystemregistration": "1.0.6"
    },
    "url": "https://packages.unity.com"
}
```

#### How do we lock the minimum version requirement to `"1.0.6"`?
<hr><br>

## Context
In the `Packages/packages-lock.json` file, there is a list of packages that the Unity project requires in order to work, known as dependencies. One of these dependencies is the "XR Interaction Subsystems" package.
<br>

Inside of the `packages-lock.json` file, the package definition looks like this:
```JSON
{
    "dependencies": {

        "com.unity.xr.interactionsubsystems": {
            "version": "1.0.1",
            "depth": 1,
            "source": "registry",
            "dependencies": {
                "com.unity.subsystemregistration": "1.0.6"
            },
            "url": "https://packages.unity.com"
        }

    }
}
```
where `"com.unity.xr.interactionsubsystems"` is the package name, written in reverse domain name notation.
i.e. `"[top-level domain].[organization].[package].[scope]"`.
<br>

You can see that the package itself has dependencies, known as secondary dependencies. In this case, it's defined as:
```JSON
"dependencies": {
    "com.unity.subsystemregistration": "1.0.6"
}
```
where `"com.unity.subsystemregistration"` is the dependency, and `"1.0.6"` is the minimum version required for the project.

**Comment by Aiden-Gaines** [comment]
@tjlauer You could always .gitignore that file and change it manually when you add packages, but that is kind of janky. It seems that the issue is caused because half the contributors have 1.0.5 on their local machine, and, for some reason, that isn't updated when you sync changes. Have you tried changing it manually on your computer to see if that fixes it?
