### ISSUE TITLE
Move Unity VR package to Steam VR

### ISSUE THREAD

**Issue by tjlauer** [tjlauer/Hospital_Simulator#66]
What is needed to switch from the `Oculus` package (currently using) to the `SteamVR` package in Unity?

Using `SteamVR` allows us to support MANY different types of headsets, as opposed to just supporting the Oculus Link.

Using `SteamVR` also allows for new headsets to be automatically supported without us needing to manually add support.

**Comment by Aiden-Gaines** [comment]
https://assetstore.unity.com/packages/tools/integration/steamvr-plugin-32647
This should be the most important thing you need. Then, just switch to the controllers/interactables provided by this package. Never used this one, but I imagine it functions similarly?
